// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package queries

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetViewerLoginResponse is returned by GetViewerLogin on success.
type GetViewerLoginResponse struct {
	// The currently authenticated user.
	Viewer *GetViewerLoginViewerUser `json:"viewer"`
}

// GetViewer returns GetViewerLoginResponse.Viewer, and is useful for accessing the field via an interface.
func (v *GetViewerLoginResponse) GetViewer() *GetViewerLoginViewerUser { return v.Viewer }

// GetViewerLoginViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type GetViewerLoginViewerUser struct {
	// The username used to login.
	Login string `json:"login"`
}

// GetLogin returns GetViewerLoginViewerUser.Login, and is useful for accessing the field via an interface.
func (v *GetViewerLoginViewerUser) GetLogin() string { return v.Login }

// The query executed by GetViewerLogin.
const GetViewerLogin_Operation = `
query GetViewerLogin {
	viewer {
		login
	}
}
`

// Pilot operation. Used by `cmd/standup.go` to resolve the authenticated
// user's login when filtering to "@me" without an explicit owner.
func GetViewerLogin(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetViewerLoginResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetViewerLogin",
		Query:  GetViewerLogin_Operation,
	}

	data_ = &GetViewerLoginResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
